import type {
  RogueliteBoss,
  RogueliteBossMutation,
  RogueliteBoon,
  RogueliteChoicePreview,
  RogueliteNodeType,
  RoguelitePlanetSkin,
  RogueliteRelic,
  RogueliteRunArchetype,
  RogueliteRunModifier,
} from "./types";

export const ROGUELITE_NODE_LABELS: Record<
  RogueliteNodeType,
  { label: string; description: string }
> = {
  boon: {
    label: "Bonus-Station",
    description:
      "Drei funkelnde Boni warten auf dich, mit klaren Sofortwerten und spaeteren Build-Hooks.",
  },
  combat: {
    label: "Sternengeplapper",
    description:
      "Ein direkter Test fuer Klicks, Schilde und Bossdruck. Solide Belohnung, solides Risiko.",
  },
  elite: {
    label: "Elite-Sog",
    description: "Hoeheres Lebensrisiko gegen Splitter, Dust und deutlich bessere Endtruhe.",
  },
  anomaly: {
    label: "Anomalie",
    description:
      "Instabile Raumfalten mit wilden Mischboni, hoher Spannung und verstecktem Langzeitwert.",
  },
  rest: {
    label: "Rastplatz",
    description:
      "Hier wandelst du Druck in Stabilitaet um: Heilung, Schild oder Vorbereitung fuer spaetere Risiken.",
  },
  merchant: {
    label: "Sternen-Haendler",
    description: "Tausche Kristallstaub gegen gezielte Power-Spikes oder Endtruhe-Qualitaet.",
  },
  relic_vault: {
    label: "Reliktkammer",
    description:
      "Ein reiner Value-Knoten: weniger Sofortkraft, dafuer viel staerkere Endbelohnungen.",
  },
  sacrifice: {
    label: "Opferaltar",
    description:
      "Die brutalsten Entscheidungen des Runs: echter Schmerz gegen echte High-Roll-Belohnungen.",
  },
  echo: {
    label: "Echo-Kammer",
    description:
      "Spiegelt den letzten Build-Schritt oder gleicht schiefe Stats fuer spaetere Stationen aus.",
  },
  meteor: {
    label: "Meteorschauer",
    description: "Schneller Staub- und Bossschub, aber fast immer mit spuerbarem Rueckstoss.",
  },
  boss_omen: {
    label: "Boss-Vorzeichen",
    description: "Liefert Bosswissen oder Bossdruck, je nachdem wie frech du den Nebel anfasst.",
  },
};

export const ROGUELITE_RUN_ARCHETYPES: RogueliteRunArchetype[] = [
  {
    id: "anomaly_weaver",
    title: "Anomalie-Weberei",
    description: "Der Run zieht Risse, Echos und weiche Chaos-Entscheidungen magisch an.",
    playstyle: "Flexibler Misch-Build mit Value aus Raumfalten.",
  },
  {
    id: "elite_hunter",
    title: "Elite-Jagd",
    description:
      "Gefaehrlichere Routen, aber dafuer mehr Belohnungsdruck und staerkere Truheraeume.",
    playstyle: "Aggressiver Run fuer Splitter- und Relikt-Hunter.",
  },
  {
    id: "merchant_orbit",
    title: "Haendler-Orbit",
    description: "Mehr Staub, mehr Shops und feinere Upgrade-Timingfenster.",
    playstyle: "Wirtschaftslastiger Run mit kontrollierten Power-Spikes.",
  },
  {
    id: "event_bloom",
    title: "Event-Bluete",
    description: "Mehr kosmische Zwischenmomente, mehr Soft-Pivots und zusaetzliche Build-Chancen.",
    playstyle: "Reaktiv und voller kleiner Richtungswechsel.",
  },
  {
    id: "bulwark_spiral",
    title: "Barrieren-Spirale",
    description: "Schild und Sicherheit stehen im Vordergrund, ohne den Bossdruck zu vergessen.",
    playstyle: "Defensiver Scaling-Run mit stabilen Kaempfen.",
  },
  {
    id: "glass_comet",
    title: "Glas-Komet",
    description: "Hohe Offensivwerte, duenne Sicherheitsnetze und explosive Belohnungsfenster.",
    playstyle: "Riskanter Burst-Run fuer mutige Entscheidungen.",
  },
];

export const ROGUELITE_RUN_MODIFIERS: RogueliteRunModifier[] = [
  {
    id: "glitter_surge",
    title: "Glitzerstrom",
    description: "Stationen schuetten etwas mehr Kristallstaub aus als gewoehnlich.",
    effectLabel: "Mehr Dust im ganzen Run",
  },
  {
    id: "omen_lens",
    title: "Vorzeichen-Linse",
    description: "Bosswissen und Bossdruck tauchen frueher und haeufiger im Run auf.",
    effectLabel: "Bossplay frueher relevant",
  },
  {
    id: "soft_shell",
    title: "Weichschale",
    description: "Der Run startet sanfter, will dich spaeter aber fuer zu viel Komfort bestrafen.",
    effectLabel: "Frueh sicher, spaet bissiger",
  },
  {
    id: "cruel_blossom",
    title: "Grausame Bluete",
    description: "Opfer- und Elite-Wert steigen, aber auch der Preis dafuer.",
    effectLabel: "Mehr Value auf harten Pfaden",
  },
];

export const ROGUELITE_BOON_PREVIEWS: Record<string, RogueliteChoicePreview> = {
  click_plus_50: {
    gains: ["+50% Klickkraft sofort"],
    costs: [],
    risks: [],
    synergyHint: "Stark fuer Glas-Komet, Aggro-Kaempfe und fruehe Bossdamage-Stacks.",
    rewardPreview: "Erleichtert Kampf- und Elite-Stationen direkt.",
  },
  first_five_double: {
    gains: ["+6 Bossschaden sofort"],
    costs: [],
    risks: [],
    synergyHint: "Gut, wenn du viele kurze, explosive Duelle suchst.",
    rewardPreview: "Hilft vor allem im Finale und bei burstigen Kaempfen.",
  },
  combo_after_ten: {
    gains: ["+7 Klicks"],
    costs: [],
    risks: ["+1 Kometendruck"],
    synergyHint: "Stark, wenn du ohnehin auf lange, aggressive Stationen spielst.",
    rewardPreview: "Mehr Tempo in Standardkaempfen und Bossskalierung.",
  },
  crit_chance_8: {
    gains: ["+8% Crit-Chance"],
    costs: [],
    risks: [],
    synergyHint: "Passt in fast jeden Klick-Build und skaliert spaeter gut mit Crit-Power.",
    rewardPreview: "Konstanter Schadensboost ohne Zusatzkosten.",
  },
  crit_power_125: {
    gains: ["+1.25 Crit-Multiplikator"],
    costs: [],
    risks: [],
    synergyHint: "Am staerksten mit schon vorhandener Crit-Chance.",
    rewardPreview: "Groesserer Bossburst und gefaehrlichere Eliten werden schneller weich.",
  },
  every_third_splitter: {
    gains: ["+10 Bossschaden sofort"],
    costs: [],
    risks: [],
    synergyHint: "Einer der staerksten Finisher fuer offensiv geformte Runs.",
    rewardPreview: "Erhoeht besonders deinen Endkampf-Payoff.",
  },
  clicks_scale_shield: {
    gains: ["Klickkraft skaliert zusaetzlich mit deinem Schild"],
    costs: [],
    risks: [],
    synergyHint: "Perfekt fuer Barrieren-Spirale und defensive Shop-Routen.",
    rewardPreview: "Macht sichere Runs trotzdem gefaehrlich.",
  },
  clicks_heal_life: {
    gains: ["+8 Leben sofort"],
    costs: [],
    risks: [],
    synergyHint: "Flickt aggressive Runs und puffert Opferentscheidungen.",
    rewardPreview: "Mehr Fehlertoleranz bis zum Boss.",
  },
  animals_x2: {
    gains: ["Passivschaden x2"],
    costs: [],
    risks: [],
    synergyHint: "Massiver Spike fuer Stall- und Moon-Animal-Builds.",
    rewardPreview: "Drueckt Basisschaden in jedem weiteren Kampf hoch.",
  },
  animals_each_station: {
    gains: ["+3 Passivschaden sofort"],
    costs: [],
    risks: [],
    synergyHint: "Skaliert solide ueber laengere Runs und sichere Routen.",
    rewardPreview: "Wird mit jeder weiteren Station wertvoller.",
  },
  elite_passive_double: {
    gains: ["+0.12 Reward-Multiplikator"],
    costs: [],
    risks: [],
    synergyHint: "Ideal fuer Elite-Jagd und harte Zweigwaehle.",
    rewardPreview: "Mehr Truhewert statt direktem Kampfschub.",
  },
  new_animal_shield: {
    gains: ["+18 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Hilft Stall-Builds, frueh nicht zu zerplatzen.",
    rewardPreview: "Mehr defensive Puffer fuer riskantere Folgepfade.",
  },
  animal_boost_per_relic: {
    gains: ["+6 Passiv pro aktivem Relikt"],
    costs: [],
    risks: [],
    synergyHint: "Besser, wenn du schon zwei starke Startreliquien traegst.",
    rewardPreview: "Direkte Skalierung aus deiner Meta-Ausrichtung.",
  },
  idle_stack_patience: {
    gains: ["+8 Passiv", "+6 Kristallstaub"],
    costs: [],
    risks: [],
    synergyHint: "Hilft Shop-Runs und langsameren Shield-Builds.",
    rewardPreview: "Mehr Staub und weicheres Midgame.",
  },
  moon_animals_boss_damage: {
    gains: ["Bossschaden skaliert zusaetzlich mit Passivwert"],
    costs: [],
    risks: [],
    synergyHint: "Der beste Gluepunkt zwischen Stall-Build und Bossfinish.",
    rewardPreview: "Hebt vor allem das Finale an.",
  },
  events_more_often: {
    gains: ["+15% Event-Chance"],
    costs: [],
    risks: [],
    synergyHint: "Perfekt fuer Event-Bluete und flexible Pivot-Runs.",
    rewardPreview: "Mehr Zwischenwahl und mehr kleine Kurskorrekturen.",
  },
  event_duration_50: {
    gains: ["+10% Event-Chance", "+5 Kristallstaub"],
    costs: [],
    risks: [],
    synergyHint: "Gut, wenn du Events aktiv fuer Sustain und Utility jagst.",
    rewardPreview: "Mehr Wert aus Event-Knoten ueber den ganzen Run.",
  },
  anomalies_double_choice: {
    gains: ["+0.05 Reward-Multiplikator"],
    costs: [],
    risks: [],
    synergyHint: "Ideal fuer Anomalie-Weberei und Value-Runs.",
    rewardPreview: "Steigert den spaeteren Truhenwert.",
  },
  reroll_every_third: {
    gains: ["+1 Reroll"],
    costs: [],
    risks: [],
    synergyHint: "Stark, wenn du gezielt nach Crit-, Shop- oder Schildlinien suchst.",
    rewardPreview: "Mehr Kontrolle ueber Boon-Auswahl.",
  },
  route_preview_plus_one: {
    gains: ["+1 Purge"],
    costs: [],
    risks: [],
    synergyHint: "Hilft bei laengeren Runs mit vielen Druckspitzen.",
    rewardPreview: "Mehr Sicherheitswerkzeug statt direkter Power.",
  },
  elite_relic_bonus: {
    gains: ["Seltene Relikte am Ende wahrscheinlicher"],
    costs: [],
    risks: [],
    synergyHint: "Am besten, wenn du bewusst Eliten ansammelst.",
    rewardPreview: "Starker Endtruhe-Booster.",
  },
  boss_telegraph: {
    gains: ["Boss-Mutationen werden sichtbar"],
    costs: [],
    risks: [],
    synergyHint: "Stark fuer Planung und fuer Runs mit knapper Defensive.",
    rewardPreview: "Weniger Blindflug im Finale.",
  },
  research_cheaper: {
    gains: ["25% guenstigere Staub-Kaeufe"],
    costs: [],
    risks: [],
    synergyHint: "Trifft besonders Haendler-Orbit und Dust-starke Routen.",
    rewardPreview: "Macht Shop- und Merchant-Knoten spuerbar besser.",
  },
  shop_costs_25: {
    gains: ["25% guenstigere Shop-Kosten"],
    costs: [],
    risks: [],
    synergyHint: "Stapelbar mit jeder dust-lastigen Route.",
    rewardPreview: "Spaetere Merchant-Stops werden effizienter.",
  },
  first_shop_free: {
    gains: ["+10 Kristallstaub sofort"],
    costs: [],
    risks: [],
    synergyHint: "Hilft Start-Runs schnell in eine sichere Form zu kommen.",
    rewardPreview: "Beschleunigt dein erstes Kauf-Fenster.",
  },
  skip_bonus_purge: {
    gains: ["+1 Purge"],
    costs: [],
    risks: [],
    synergyHint: "Gut fuer Runs mit viel Kometendruck und Fluchlinien.",
    rewardPreview: "Mehr Cleanup statt rohem Schaden.",
  },
  rest_bonus_shard: {
    gains: ["+1 Bonus-Splitter am Ende"],
    costs: [],
    risks: [],
    synergyHint: "Sehr gut fuer sichere, kontrollierte Routen mit mehreren Rests.",
    rewardPreview: "Belohnt defensive Pfadwahl direkt in der Truhe.",
  },
  duplicates_to_dust: {
    gains: ["+12 Kristallstaub"],
    costs: [],
    risks: [],
    synergyHint: "Niedrigeres Ceiling, aber super fuers Stabilisieren.",
    rewardPreview: "Mehr Kaufkraft ohne Zusatzrisiko.",
  },
  starting_shield_30: {
    gains: ["+30 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Top fuer Schild-Skalierung und riskante fruehe Eliten.",
    rewardPreview: "Sichert das fruehe Midgame ab.",
  },
  shield_each_station: {
    gains: ["+12 Schild sofort"],
    costs: [],
    risks: [],
    synergyHint: "Wird mit jedem Folgeknoten wertvoller, wenn du Schild in Schaden umwandelst.",
    rewardPreview: "Stabilitaet ueber den ganzen Run.",
  },
  shield_burst_aoe: {
    gains: ["Bossschaden skaliert mit Schild"],
    costs: [],
    risks: [],
    synergyHint: "Klebt Defense und Finish eng zusammen.",
    rewardPreview: "Gross fuer sichere Boss-Kills.",
  },
  boss_damage_minus_20: {
    gains: ["+8 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Hilft vor allem fragilen Runs bis ueber die Ziellinie.",
    rewardPreview: "Weicheres Finale, weniger Throw-Gefahr.",
  },
  revive_once: {
    gains: ["+16 Leben", "+16 Max-Leben"],
    costs: [],
    risks: [],
    synergyHint: "Sicherheitsnetz fuer High-Risk-Routen und Opferaltare.",
    rewardPreview: "Einer der besten Anti-Defeat-Picks.",
  },
  heal_rest_double: {
    gains: ["+1 Heilcharge"],
    costs: [],
    risks: [],
    synergyHint: "Macht Rest-Knoten zu echten Power-Resets.",
    rewardPreview: "Mehr Sustain fuer lange Runs.",
  },
  curse_barrier: {
    gains: ["+20 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Passt in Fluch-Runs, die den Rueckstoss sofort puffern wollen.",
    rewardPreview: "Opfer- und Risk-Events werden sicherer.",
  },
  low_life_crit: {
    gains: ["+6% Crit-Chance"],
    costs: [],
    risks: [],
    synergyHint: "Stark fuer angeschlagene Aggro-Runs mit wenig Reserve.",
    rewardPreview: "Mehr Comeback-Potenzial unter Druck.",
  },
  double_shards_boss_mutation: {
    gains: ["+2 Bonus-Splitter"],
    costs: [],
    risks: ["+1 Fluchzaehler", "+6 Kometendruck"],
    synergyHint: "Reiner Endtruhe-Greed fuer mutige Runs.",
    rewardPreview: "Sehr hoher Siegspayoff, sehr wenig Komfort.",
  },
  sacrifice_shield_power: {
    gains: ["+10 Klicks"],
    costs: ["-12 Schild"],
    risks: [],
    synergyHint: "Stark, wenn Schild gerade weniger wichtig als Tempo ist.",
    rewardPreview: "Direkter Power-Spike fuer offensive Linien.",
  },
  lose_life_legendary: {
    gains: ["seltene Relikte wahrscheinlicher", "+0.08 Reward-Multiplikator"],
    costs: ["20% aktuelles Leben"],
    risks: ["Erhoeht Fluch- und Snowball-Risiko"],
    synergyHint: "Eine echte High-Roll-Wette fuer stabile oder revive-starke Runs.",
    rewardPreview: "Massiv besserer Endloot.",
  },
  take_curse_skin_roll: {
    gains: ["+1 Bonus-Splitter", "+0.05 Reward-Multiplikator"],
    costs: [],
    risks: ["Erhoeht Fluchzaehler"],
    synergyHint: "Stark fuer Reward-Greed, wenn du den Fluch tragen kannst.",
    rewardPreview: "Mehr Rohwert in der Endtruhe.",
  },
  starrain_autoclick: {
    gains: ["+12 Klicks", "+4 Passiv"],
    costs: [],
    risks: [],
    synergyHint: "Einfach starke Allround-Offense.",
    rewardPreview: "Drueckt fast jeden normalen Knoten leichter weg.",
  },
  even_station_copy: {
    gains: ["+5 Klicks", "+5 Passiv"],
    costs: [],
    risks: [],
    synergyHint: "Sauberer Gluepick fuer hybride Builds.",
    rewardPreview: "Hilft in jedem Folgeakt.",
  },
  highest_feeds_lowest: {
    gains: ["Dein staerkster Kernwert fuettert den schwaechsten"],
    costs: [],
    risks: [],
    synergyHint: "Repariert schiefe Build-Verteilungen sehr effizient.",
    rewardPreview: "Mehr Balance vor Boss- und Elite-Peaks.",
  },
  freeze_boss_phase: {
    gains: ["+18 Bossschaden"],
    costs: [],
    risks: [],
    synergyHint: "Direkter Finisher ohne Schnickschnack.",
    rewardPreview: "Verkuerzt das Finale spuerbar.",
  },
  triad_set_bonus: {
    gains: ["Bei 3 Kategorien: +6 Klicks, +6 Passiv, +10 Schild"],
    costs: [],
    risks: [],
    synergyHint: "Belohnt breite, kreative Build-Pfade statt Tunnelblick.",
    rewardPreview: "Grosses Midgame-Scaling bei kluger Diversitaet.",
  },
};

export const ROGUELITE_RELICS: RogueliteRelic[] = [
  {
    id: "kometenherz",
    name: "Kometenherz",
    description: "Du startest mit einem extra Schimmer-Schild.",
    rarity: "rare",
    shortLabel: "+30 Start-Schild",
  },
  {
    id: "pfotenkompass",
    name: "Pfotenkompass",
    description: "Zeigt mehr Infos ueber kommende Wege und Gefahren.",
    rarity: "common",
    shortLabel: "Bessere Routeninfo",
  },
  {
    id: "nebelglas",
    name: "Nebelglas",
    description: "Anomalien tauchen haeufiger auf und sind etwas freundlicher.",
    rarity: "rare",
    shortLabel: "Mehr Anomalien",
  },
  {
    id: "funkelzahn",
    name: "Funkelzahn",
    description: "Mehr Start-Crit-Chance und ein bisschen Crit-Kraft.",
    rarity: "common",
    shortLabel: "+Crit Start",
  },
  {
    id: "mondfaden",
    name: "Mondfaden",
    description: "Schenkt eine freie Heilcharge fuer jeden frischen Run.",
    rarity: "common",
    shortLabel: "+1 Heilcharge",
  },
  {
    id: "splitterbeutel",
    name: "Splitterbeutel",
    description: "Am Ende fallen mehr Galaxie-Splitter aus dem Run.",
    rarity: "rare",
    shortLabel: "+1 End-Splitter",
  },
  {
    id: "sternennaht",
    name: "Sternennaht",
    description: "Jeder Run startet mit einem zusaetzlichen Bonus-Reroll.",
    rarity: "epic",
    shortLabel: "+1 Reroll",
  },
  {
    id: "leerefeder",
    name: "Leerefeder",
    description: "Der Boss wird weicher, dafuer werden normale Stationen bissiger.",
    rarity: "epic",
    shortLabel: "Boss leichter",
  },
];

export const ROGUELITE_PLANET_SKINS: RoguelitePlanetSkin[] = [
  {
    id: "kometenzucker",
    name: "Kometenzucker",
    description: "Suesse Kometenstreifen ueberziehen deinen Hauptplaneten.",
    previewImage: "/assets/planets/18_zuckerstern_garten.webp",
  },
  {
    id: "aurora_bruch",
    name: "Aurora-Bruch",
    description: "Leuchtende Scherben in goldener Nordlicht-Farbe.",
    previewImage: "/assets/planets/09_auroras_goldene_krone.webp",
  },
  {
    id: "mondscherbe",
    name: "Mondscherbe",
    description: "Ein zartes Mondlicht mit silbrigem Glanz.",
    previewImage: "/assets/planets/12_kirschmond_planet.webp",
  },
  {
    id: "nebelflausch",
    name: "Nebelflausch",
    description: "Vertraeumte Wolken und milchige Sternenspuren.",
    previewImage: "/assets/planets/11_sternenwatte_planet.webp",
  },
  {
    id: "sternensirup",
    name: "Sternensirup",
    description: "Warme Karamell-Funken mit kosmischem Glanz.",
    previewImage: "/assets/planets/15_honigstern_planet.webp",
  },
  {
    id: "pfotenorbit",
    name: "Pfotenorbit",
    description: "Pfotenfoermige Umlaufbahnen fuer extra Niedlichkeit.",
    previewImage: "/assets/planets/13_glitzerpfoten_planet.webp",
  },
];

export const ROGUELITE_BOSSES: RogueliteBoss[] = [
  {
    id: "scherbenkomet",
    name: "Scherbenkomet",
    title: "Splittersturm des Nachthimmels",
    description: "Ein rasender Komet, der Schilde aufreissen und Splitter umleiten kann.",
    baseDifficulty: 118,
  },
  {
    id: "schlafwandler_komet",
    name: "Schlafwandler-Komet",
    title: "Der flauschige Finsternisschweif",
    description: "Schiebt deine Heilung weg und drueckt sanften, aber schweren Druck auf den Run.",
    baseDifficulty: 124,
  },
  {
    id: "nebelprisma",
    name: "Nebelprisma",
    title: "Gebrochene Farben im leeren All",
    description: "Verzerrt Krits, passiven Schaden und Rhythmus.",
    baseDifficulty: 128,
  },
  {
    id: "glitch_meteor",
    name: "Glitch-Meteor",
    title: "Knisternder Fehlerkern",
    description: "Ein chaotischer Brocken, der Eventstille und Spiegelbilder erzeugt.",
    baseDifficulty: 132,
  },
];

export const ROGUELITE_BOSS_MUTATIONS: RogueliteBossMutation[] = [
  {
    id: "shield_break",
    name: "Schildbruch",
    description: "Startet den Bosskampf mit weniger Schild.",
  },
  {
    id: "crit_resist",
    name: "Crit-Resistenz",
    description: "Ein Teil deiner Kritkraft verpufft im Raum.",
  },
  {
    id: "event_silence",
    name: "Eventstille",
    description: "Event-Chance hilft im Bosskampf kaum noch.",
  },
  {
    id: "healing_lock",
    name: "Heilungsblock",
    description: "Heilcharges sind im Bosskampf nur halb so stark.",
  },
  {
    id: "splitterregen",
    name: "Splitterregen",
    description: "Der Boss streut Druck, schenkt aber auch mehr End-Splitter.",
  },
  {
    id: "spiegelphase",
    name: "Spiegelphase",
    description: "Dein hoechster Wert wird leicht abgeschwaecht.",
  },
];

export const ROGUELITE_EVENT_POOL = [
  {
    id: "saccharin_wormhole",
    title: "Zuckerwurmloch",
    description: "Ein suesses Wurmloch lockt mit Tempo oder Sicherheit.",
    choices: [
      {
        id: "wormhole_hasten",
        title: "Tempo trinken",
        description: "+1 Reroll und +12% Klicks, aber +6 Kometendruck.",
      },
      {
        id: "wormhole_anchor",
        title: "Ankern",
        description: "+16 Schild und -4 Kometendruck.",
      },
    ],
  },
  {
    id: "dream_petals",
    title: "Traumblatt-Schauer",
    description: "Leuchtende Blueten wollen gehegt oder geopfert werden.",
    choices: [
      {
        id: "petals_heal",
        title: "Ueber dem Herzen sammeln",
        description: "Heile 22 Leben und +5% Event-Chance.",
      },
      {
        id: "petals_trade",
        title: "Zu Staub zerreiben",
        description: "+18 Kristallstaub und +1 Purge.",
      },
    ],
  },
  {
    id: "void_kittens",
    title: "Leere-Kaetzchen",
    description: "Drei winzige Leere-Kaetzchen bieten Hilfe gegen ein kleines Opfer.",
    choices: [
      {
        id: "kittens_crit",
        title: "Pfotenpact",
        description: "-8 Leben, dafuer +10% Crit-Chance.",
      },
      {
        id: "kittens_guard",
        title: "Kuschelschutz",
        description: "+24 Schild und +1 Heilcharge.",
      },
    ],
  },
];

export const ROGUELITE_BOONS: RogueliteBoon[] = [
  {
    id: "click_plus_50",
    title: "+50% Klicks",
    description: "Deine Klick-Kraft wird sofort deutlich staerker.",
    category: "click",
    rarity: "common",
  },
  {
    id: "first_five_double",
    title: "Erste 5 Klicks doppelt",
    description: "Jeder frische Kampf startet mit extra Wumms.",
    category: "click",
    rarity: "rare",
  },
  {
    id: "combo_after_ten",
    title: "Combo ab 10 Klicks",
    description: "Laengere Kaempfe werden immer gefaehrlicher fuer Gegner.",
    category: "click",
    rarity: "rare",
  },
  {
    id: "crit_chance_8",
    title: "Crit-Chance +8%",
    description: "Mehr funkelnde Volltreffer.",
    category: "click",
    rarity: "common",
  },
  {
    id: "crit_power_125",
    title: "Crits staerker",
    description: "Kritische Treffer schlagen besonders hart ein.",
    category: "click",
    rarity: "rare",
  },
  {
    id: "every_third_splitter",
    title: "Jeder dritte Klick splittert",
    description: "Jeder dritte Treffer addiert Boss-Schaden.",
    category: "click",
    rarity: "epic",
  },
  {
    id: "clicks_scale_shield",
    title: "Klicks skalieren mit Schilden",
    description: "Schutz wird zur Angriffskraft.",
    category: "click",
    rarity: "epic",
  },
  {
    id: "clicks_heal_life",
    title: "Klicks heilen",
    description: "Aggressives Spielen flickt kleine Risse.",
    category: "click",
    rarity: "epic",
  },
  {
    id: "animals_x2",
    title: "Tiere x2",
    description: "Passiver Druck springt auf kuschelige Hochtouren.",
    category: "animals",
    rarity: "common",
  },
  {
    id: "animals_each_station",
    title: "Tiere +1 pro Station",
    description: "Mit jeder Station waechst dein passiver Stall.",
    category: "animals",
    rarity: "rare",
  },
  {
    id: "elite_passive_double",
    title: "Nach Elite passiv doppelt",
    description: "Mut wird spaeter mit gewaltigem Tempo bezahlt.",
    category: "animals",
    rarity: "rare",
  },
  {
    id: "new_animal_shield",
    title: "Neue Tiere geben Schild",
    description: "Jeder Zuwachs schuetzt dein Herz.",
    category: "animals",
    rarity: "common",
  },
  {
    id: "animal_boost_per_relic",
    title: "Tier-Boost pro Relikt",
    description: "Deine ausgeruesteten Relikte fuettern den Stall.",
    category: "animals",
    rarity: "rare",
  },
  {
    id: "idle_stack_patience",
    title: "Geduld stapelt LPS",
    description: "Wenn du nicht kaufst, steigt der passive Druck.",
    category: "animals",
    rarity: "epic",
  },
  {
    id: "moon_animals_boss_damage",
    title: "Mondtiere geben Bossschaden",
    description: "Passives Glitzern brennt direkt in den Bosskern.",
    category: "animals",
    rarity: "epic",
  },
  {
    id: "events_more_often",
    title: "Events haeufiger",
    description: "Der Kosmos zeigt dir mehr wilde Gelegenheiten.",
    category: "tempo",
    rarity: "common",
  },
  {
    id: "event_duration_50",
    title: "Eventdauer +50%",
    description: "Deine starken Momente halten laenger an.",
    category: "tempo",
    rarity: "rare",
  },
  {
    id: "anomalies_double_choice",
    title: "Anomalien geben doppelte Wahl",
    description: "Instabile Risse werden grosszuegiger.",
    category: "tempo",
    rarity: "epic",
  },
  {
    id: "reroll_every_third",
    title: "Reroll jede 3. Station",
    description: "Regelmaessige Kurskorrektur fuer schlechte Angebote.",
    category: "tempo",
    rarity: "rare",
  },
  {
    id: "route_preview_plus_one",
    title: "Route-Vorschau +1",
    description: "Du siehst frueher, welcher Ast gefaehrlich wird.",
    category: "tempo",
    rarity: "common",
  },
  {
    id: "elite_relic_bonus",
    title: "Elite-Stationen droppen besser",
    description: "Eliten verbessern deine End-Reliktwahl.",
    category: "tempo",
    rarity: "epic",
  },
  {
    id: "boss_telegraph",
    title: "Boss-Telegraph",
    description: "Das naechste Boss-Muster wird sichtbar.",
    category: "tempo",
    rarity: "rare",
  },
  {
    id: "research_cheaper",
    title: "Forschung billiger",
    description: "Haendler und riskante Technik fressen weniger Staub.",
    category: "economy",
    rarity: "common",
  },
  {
    id: "shop_costs_25",
    title: "Shop-Kosten -25%",
    description: "Dein Staub reicht deutlich weiter.",
    category: "economy",
    rarity: "rare",
  },
  {
    id: "first_shop_free",
    title: "Erstes Shop-Item gratis",
    description: "Einmal pro Run bekommst du einen sanften Vorsprung.",
    category: "economy",
    rarity: "epic",
  },
  {
    id: "skip_bonus_purge",
    title: "Skippen gibt Purge",
    description: "Sogar Verzicht wird hier noch nuetzlich.",
    category: "economy",
    rarity: "rare",
  },
  {
    id: "rest_bonus_shard",
    title: "Rastplaetze geben Bonus-Splitter",
    description: "Sanfte Wege zahlen sich spaeter aus.",
    category: "economy",
    rarity: "epic",
  },
  {
    id: "duplicates_to_dust",
    title: "Duplikate geben Staub",
    description: "Nichts geht verloren, wenn ein Bonus wiederkehrt.",
    category: "economy",
    rarity: "common",
  },
  {
    id: "starting_shield_30",
    title: "Startschild +30",
    description: "Die Reise beginnt mit einem warmen Schutzmantel.",
    category: "defense",
    rarity: "common",
  },
  {
    id: "shield_each_station",
    title: "Jede Station +12 Schild",
    description: "Dein Schutz waechst Schritt fuer Schritt.",
    category: "defense",
    rarity: "rare",
  },
  {
    id: "shield_burst_aoe",
    title: "Schild platzt als Welle",
    description: "Verbrauchte Barrieren lassen Splitter zurueck.",
    category: "defense",
    rarity: "epic",
  },
  {
    id: "boss_damage_minus_20",
    title: "Bossschaden -20%",
    description: "Der Endgegner fuehlt sich ein bisschen weniger unfair an.",
    category: "defense",
    rarity: "rare",
  },
  {
    id: "revive_once",
    title: "Einmalige Wiederbelebung",
    description: "Ein letzter weicher Atemzug, wenn alles kippt.",
    category: "defense",
    rarity: "legendary",
  },
  {
    id: "heal_rest_double",
    title: "Rastheilung verdoppelt",
    description: "Erholung wird aussergewoehnlich effizient.",
    category: "defense",
    rarity: "rare",
  },
  {
    id: "curse_barrier",
    title: "Nach Fluch sofort Barriere",
    description: "Mutige Entscheidungen geben direkten Schutz.",
    category: "defense",
    rarity: "epic",
  },
  {
    id: "low_life_crit",
    title: "Unter 30% Leben +Crit",
    description: "Gefahr macht dich ploetzlich sehr scharf.",
    category: "defense",
    rarity: "rare",
  },
  {
    id: "double_shards_boss_mutation",
    title: "Doppelte Splitter, haerterer Boss",
    description: "Groesserer Preis, groessere Gefahr.",
    category: "risk",
    rarity: "legendary",
  },
  {
    id: "sacrifice_shield_power",
    title: "Schild fuer Schaden opfern",
    description: "Du gibst Sicherheit ab und bekommst rohe Gewalt.",
    category: "risk",
    rarity: "epic",
  },
  {
    id: "lose_life_legendary",
    title: "20% Leben fuer Legendaer",
    description: "Ein drastischer Deal mit hohem Glanz.",
    category: "risk",
    rarity: "legendary",
  },
  {
    id: "take_curse_skin_roll",
    title: "Fluch fuer Truhenwert",
    description: "Mehr Endbeute gegen hoehere Verderbnis.",
    category: "risk",
    rarity: "epic",
  },
  {
    id: "starrain_autoclick",
    title: "Sternenregen klickt automatisch",
    description: "Ein Teil des Runs spielt sich wie von selbst.",
    category: "exotic",
    rarity: "epic",
  },
  {
    id: "even_station_copy",
    title: "Gerade Stationen kopieren den letzten Bonus halb",
    description: "Dein letzter Gluecksmoment hallt weiter.",
    category: "exotic",
    rarity: "legendary",
  },
  {
    id: "highest_feeds_lowest",
    title: "Hoechster Stat speist niedrigsten",
    description: "Der Run balanciert seine Extreme selbst aus.",
    category: "exotic",
    rarity: "epic",
  },
  {
    id: "freeze_boss_phase",
    title: "Boss-Komet friert 1 Phase ein",
    description: "Der Endgegner stolpert kurz ueber die Zeit.",
    category: "exotic",
    rarity: "legendary",
  },
  {
    id: "triad_set_bonus",
    title: "Bonus-Triad gibt Set-Bonus",
    description: "Drei verschiedene Kategorien verschmelzen zu Harmonie.",
    category: "exotic",
    rarity: "rare",
  },
];
