import { Animal } from "./types";

export const INITIAL_ANIMALS: Animal[] = [
  {
    id: "bunny",
    name: "Wooly Bunny",
    germanName: "Wolliges Häschen",
    emoji: "🐰",
    image: "/assets/animals/bunny.png",
    baseCost: 15,
    costMultiplier: 1.15,
    baseLps: 0.1,
    count: 0,
    description: "Nibbles on sweet moss and hops around.",
    germanDescription: "Knabbert an süßem Moos und hoppelt fröhlich.",
    color: "bg-pink-50 text-pink-600 border-pink-100 selection:bg-pink-100",
  },
  {
    id: "chick",
    name: "Pastel Chick",
    germanName: "Pastell-Küken",
    emoji: "🐤",
    image: "/assets/animals/chick.png",
    baseCost: 100,
    costMultiplier: 1.15,
    baseLps: 0.6,
    count: 0,
    description: "Peeps happily and looks for tiny star bits.",
    germanDescription: "Piepst herzerwärmend und sucht glitzernde Krümel.",
    color: "bg-yellow-50 text-yellow-600 border-yellow-105 selection:bg-yellow-100",
  },
  {
    id: "cat",
    name: "Slumber Kitten",
    germanName: "Schlummer-Kätzchen",
    emoji: "🐱",
    image: "/assets/animals/cat.png",
    baseCost: 700,
    costMultiplier: 1.15,
    baseLps: 3.5,
    count: 0,
    description: "Purrs at the rhythm of stellar starlight.",
    germanDescription: "Schnurrt sanft im Rhythmus des kosmischen Sternenstaubs.",
    color: "bg-indigo-50 text-indigo-600 border-indigo-100 selection:bg-indigo-100",
  },
  {
    id: "frog",
    name: "Chubby Frog",
    germanName: "Kuller-Frosch",
    emoji: "🐸",
    image: "/assets/animals/frog.png",
    baseCost: 4500,
    costMultiplier: 1.15,
    baseLps: 18.0,
    count: 0,
    description: "Hops around fluffy pastel clouds.",
    germanDescription: "Hüpft auf weichen, flauschigen Schäfchenwolken.",
    color: "bg-emerald-50 text-emerald-600 border-emerald-100 selection:bg-emerald-100",
  },
  {
    id: "koala",
    name: "Eucalyptus Koala",
    germanName: "Süßer Koala",
    emoji: "🐨",
    image: "/assets/animals/koala.png",
    baseCost: 28000,
    costMultiplier: 1.15,
    baseLps: 90.0,
    count: 0,
    description: "Hugs the planet and dreams of cozy forests.",
    germanDescription: "Klammert sich fest und träumt von duftenden Wäldern.",
    color: "bg-slate-100 text-slate-600 border-slate-205 selection:bg-slate-200",
  },
  {
    id: "panda",
    name: "Fluffy Panda",
    germanName: "Flausch-Panda",
    emoji: "🐼",
    image: "/assets/animals/panda.png",
    baseCost: 180000,
    costMultiplier: 1.15,
    baseLps: 450.0,
    count: 0,
    description: "Rolls around happily in stellar meadows.",
    germanDescription: "Kugelt sich glücklich im weichen Gras herum.",
    color: "bg-zinc-100 text-zinc-600 border-zinc-200 selection:bg-zinc-200",
  },
  {
    id: "unicorn",
    name: "Rainbow Unicorn",
    germanName: "Regenbogen-Einhorn",
    emoji: "🦄",
    image: "/assets/animals/unicorn.png",
    baseCost: 1100000,
    costMultiplier: 1.15,
    baseLps: 2200.0,
    count: 0,
    description: "Spreads rainbow glow and sparkly magic.",
    germanDescription: "Versprüht zauberhaften Glitzerregen und Glückseligkeit.",
    color: "bg-purple-50 text-purple-600 border-purple-100 selection:bg-purple-100",
  },
  {
    id: "hamster",
    name: "Nugget Hamster",
    germanName: "Nugget-Hamster",
    emoji: "🐹",
    image: "/assets/animals/hamster.png",
    baseCost: 6500000,
    costMultiplier: 1.15,
    baseLps: 11000.0,
    count: 0,
    description: "Stores star energy in its tiny cheeks.",
    germanDescription: "Speichert Sternenstaub-Energie in seinen süßen Bäckchen.",
    color: "bg-amber-50 text-amber-600 border-amber-150",
  },
  {
    id: "fox",
    name: "Cinnamon Fox",
    germanName: "Zimt-Füchslein",
    emoji: "🦊",
    image: "/assets/animals/fox.png",
    baseCost: 38000000,
    costMultiplier: 1.15,
    baseLps: 55000.0,
    count: 0,
    description: "Curling its tail around warm stardust.",
    germanDescription: "Kringelt seinen weichen Schwanz um warmen Sternenstaub.",
    color: "bg-orange-50 text-orange-600 border-orange-150",
  },
  {
    id: "bear",
    name: "Honey Bear",
    germanName: "Brumm-Bärchen",
    emoji: "🐻",
    image: "/assets/animals/bear.png",
    baseCost: 220000000,
    costMultiplier: 1.16,
    baseLps: 280000.0,
    count: 0,
    description: "Gathers sweet celestial honey from nebula hives.",
    germanDescription: "Sammelt himmlisch süßen Honig aus schimmernden Nebeln.",
    color: "bg-yellow-50 text-amber-700 border-yellow-200",
  },
  {
    id: "alpaca",
    name: "Fluffy Alpaca",
    germanName: "Flausch-Alpaka",
    emoji: "🦙",
    image: "/assets/animals/alpaca.png",
    baseCost: 1300000000,
    costMultiplier: 1.16,
    baseLps: 1400000.0,
    count: 0,
    description: "Clowdy wool that absorbs comet whispers.",
    germanDescription: "Besitzt wolkenähnliche Wolle, die das Kometenflüstern speichert.",
    color: "bg-pink-50 text-pink-700 border-pink-200",
  },
  {
    id: "penguin",
    name: "Sliding Penguin",
    germanName: "Kuller-Pinguin",
    emoji: "🐧",
    image: "/assets/animals/penguin.png",
    baseCost: 8000000000,
    costMultiplier: 1.17,
    baseLps: 7000000.0,
    count: 0,
    description: "Slides elegantly on rings of ice.",
    germanDescription: "Rutscht gut gelaunt auf kühlen Eisringen entlang.",
    color: "bg-sky-50 text-sky-700 border-sky-200",
  },
  {
    id: "sloth",
    name: "Dreamy Sloth",
    germanName: "Schluffi-Faultier",
    emoji: "🦥",
    image: "/assets/animals/sloth.png",
    baseCost: 50000000000,
    costMultiplier: 1.17,
    baseLps: 35000000.0,
    count: 0,
    description: "Hangs on space branches in peaceful slumber.",
    germanDescription: "Hängt an Sternenästen und schläft seelenruhig.",
    color: "bg-stone-55 text-stone-600 border-stone-200",
  },
  {
    id: "hedgehog",
    name: "Prickly Cookie",
    germanName: "Stachel-Keks",
    emoji: "🦔",
    image: "/assets/animals/hedgehog.png",
    baseCost: 320000000000,
    costMultiplier: 1.18,
    baseLps: 180000000.0,
    count: 0,
    description: "Rolls up into an adorable sparkly ball.",
    germanDescription: "Rollt sich zu einer glitzernden, niedlichen Kugel zusammen.",
    color: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "seal",
    name: "Chubby Seal",
    germanName: "Kuller-Robbe",
    emoji: "🦭",
    image: "/assets/animals/seal.png",
    baseCost: 2000000000000,
    costMultiplier: 1.18,
    baseLps: 950000000.0,
    count: 0,
    description: "Bounces with joy on cosmic bubble wrap.",
    germanDescription: "Kullert glücklich auf kleinen kosmischen Seifenblasen.",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    id: "sheep",
    name: "Cloudy Sheep",
    germanName: "Wölkchen-Schaf",
    emoji: "🐑",
    image: "/assets/animals/sheep.png",
    baseCost: 13000000000000,
    costMultiplier: 1.18,
    baseLps: 5000000000.0,
    count: 0,
    description: "Looks exactly like a fluffy space cloud.",
    germanDescription: "Sieht aus wie ein kleines Stückchen sanfter Abendhimmel.",
    color: "bg-slate-55 text-slate-700 border-slate-200",
  },
  {
    id: "otter",
    name: "Tickle Otter",
    germanName: "Kitzel-Otter",
    emoji: "🦦",
    image: "/assets/animals/otter.png",
    baseCost: 85000000000000,
    costMultiplier: 1.19,
    baseLps: 26000000000.0,
    count: 0,
    description: "Holds hands in the river of starlight.",
    germanDescription: "Hält Händchen im sanften Fluss aus purem Sternenlicht.",
    color: "bg-indigo-50 text-indigo-700 border-indigo-200",
  },
  {
    id: "deer",
    name: "Forest Fawn",
    germanName: "Wald-Rehlein",
    emoji: "🦌",
    image: "/assets/animals/deer.png",
    baseCost: 550000000000000,
    costMultiplier: 1.19,
    baseLps: 140000000000.0,
    count: 0,
    description: "Grows tiny glowing constellations on its back.",
    germanDescription: "Trägt kleine leuchtende Sternbilder auf seinem süßen Fell.",
    color: "bg-amber-50 text-amber-800 border-amber-250",
  },
  {
    id: "dino",
    name: "Tiny Dino",
    germanName: "Zwerg-Dino",
    emoji: "🦖",
    image: "/assets/animals/dino.png",
    baseCost: 3500000000000000,
    costMultiplier: 1.19,
    baseLps: 750000000000.0,
    count: 0,
    description: "Roars with the tiniest cute squeak.",
    germanDescription: "Brüllt wie ein gänzlich furchtloser Mini-Vulkan.",
    color: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    id: "duck",
    name: "Squeaky Quacker",
    germanName: "Quack-Entchen",
    emoji: "🦆",
    image: "/assets/animals/duck.png",
    baseCost: 22000000000000000,
    costMultiplier: 1.20,
    baseLps: 4200000000000.0,
    count: 0,
    description: "Splashes in warm milk canals.",
    germanDescription: "Schwimmt schnatternd im wohlig warmen Sternenmilch-Kanal.",
    color: "bg-yellow-50 text-yellow-700 border-yellow-250",
  },
  {
    id: "ladybug",
    name: "Lucky Beetle",
    germanName: "Pünktchen-Käfer",
    emoji: "🐞",
    image: "/assets/animals/ladybug.png",
    baseCost: 150000000000000000,
    costMultiplier: 1.20,
    baseLps: 24000000000000.0,
    count: 0,
    description: "Brings good fortune to every space garden.",
    germanDescription: "Bringt glitzerndes Glück in jeden kosmischen Garten.",
    color: "bg-rose-50 text-rose-700 border-rose-200",
  },
  {
    id: "bee",
    name: "Buzzing Honeybee",
    germanName: "Süßes Bienchen",
    emoji: "🐝",
    image: "/assets/animals/bee.png",
    baseCost: 1000000000000000000,
    costMultiplier: 1.20,
    baseLps: 130000000000000.0,
    count: 0,
    description: "Flutters about pollinating pastel blooms.",
    germanDescription: "Bestäubt tanzend die allerschönsten Seerosen.",
    color: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "pig",
    name: "Piggy Wiggy",
    germanName: "Rosa Kuschelschwein",
    emoji: "🐷",
    image: "/assets/animals/pig.png",
    baseCost: 7.0e18,
    costMultiplier: 1.21,
    baseLps: 7.5e14,
    count: 0,
    description: "Loves mudbaths in sparkling hot springs.",
    germanDescription: "Wühlt am liebsten in glitzerndem Thermalbäderschlamm herum.",
    color: "bg-pink-50 text-pink-700 border-pink-200",
  },
  {
    id: "puppy",
    name: "Paw Puppeteer",
    germanName: "Tapsi-Welpe",
    emoji: "🐶",
    image: "/assets/animals/puppy.png",
    baseCost: 4.8e19,
    costMultiplier: 1.21,
    baseLps: 4.5e15,
    count: 0,
    description: "Wags its tail at supersonic speed.",
    germanDescription: "Wedelt so schnell mit dem Schwanz, dass Sterne funkeln.",
    color: "bg-orange-50 text-orange-700 border-orange-200",
  },
  {
    id: "squirrel",
    name: "Hazelnut Scurrier",
    germanName: "Knusper-Hörnchen",
    emoji: "🐿️",
    image: "/assets/animals/squirrel.png",
    baseCost: 3.2e20,
    costMultiplier: 1.21,
    baseLps: 2.5e16,
    count: 0,
    description: "Hides golden glowing space nuts.",
    germanDescription: "Versteckt goldene Zaubernüsse im galaktischen Boden.",
    color: "bg-amber-50 text-amber-800 border-amber-200",
  },
  {
    id: "mouse",
    name: "Sugar Mouse",
    germanName: "Zucker-Mäuschen",
    emoji: "🐭",
    image: "/assets/animals/mouse.png",
    baseCost: 2.2e21,
    costMultiplier: 1.22,
    baseLps: 1.4e17,
    count: 0,
    description: "Squeaks sweet lullabies to sleeping planets.",
    germanDescription: "Piepst Melodien für schlafende Monde und Zwergsterne.",
    color: "bg-zinc-50 text-zinc-600 border-zinc-200",
  },
  {
    id: "turtle",
    name: "Cosmic Shellback",
    germanName: "Trödel-Schildi",
    emoji: "🐢",
    image: "/assets/animals/turtle.png",
    baseCost: 1.5e22,
    costMultiplier: 1.22,
    baseLps: 8.5e17,
    count: 0,
    description: "Carries a miniature ecosystem on its shell.",
    germanDescription: "Trägt eine winzige Tropeninsel spazieren.",
    color: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    id: "owl",
    name: "Sage Gazer",
    germanName: "Glubsch-Eule",
    emoji: "🦉",
    image: "/assets/animals/owl.png",
    baseCost: 1.0e23,
    costMultiplier: 1.22,
    baseLps: 5.0e18,
    count: 0,
    description: "Harnesses wisecracking cosmic insight.",
    germanDescription: "Schaut majestätisch tief in die unendlichen Weiten.",
    color: "bg-indigo-50 text-indigo-700 border-indigo-200",
  },
  {
    id: "dolphin",
    name: "Splash Glitter",
    germanName: "Glitzer-Delfin",
    emoji: "🐬",
    image: "/assets/animals/dolphin.png",
    baseCost: 7.0e23,
    costMultiplier: 1.15,
    baseLps: 3.0e19,
    count: 0,
    description: "Leaps through nebulas leaving sparkly trails.",
    germanDescription: "Springt elegant durch Wolken aus buntem Sternenstaub.",
    color: "bg-sky-50 text-sky-700 border-sky-200",
  },
  {
    id: "whale",
    name: "Nebula Whale",
    germanName: "Himmels-Wal",
    emoji: "🐳",
    image: "/assets/animals/whale.png",
    baseCost: 4.8e24,
    costMultiplier: 1.23,
    baseLps: 1.8e20,
    count: 0,
    description: "Sings ultrasonic stellar tunes.",
    germanDescription: "Singt Lieder, die ganze Galaxien zum Leuchten bringen.",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    id: "butterfly",
    name: "Nectar Flutter",
    germanName: "Flatter-Mops",
    emoji: "🦋",
    image: "/assets/animals/butterfly.png",
    baseCost: 3.2e25,
    costMultiplier: 1.23,
    baseLps: 1.0e21,
    count: 0,
    description: "Gently bats sparkly wings of light.",
    germanDescription: "Sorgt für sanfte Wirbelstürme aus buntem Glückspuder.",
    color: "bg-purple-50 text-purple-700 border-purple-200",
  },
  {
    id: "elephant",
    name: "Bouncing Ellie",
    germanName: "Kuller-Kathi",
    emoji: "🐘",
    image: "/assets/animals/elephant.png",
    baseCost: 2.2e26,
    costMultiplier: 1.23,
    baseLps: 5.5e21,
    count: 0,
    description: "Trumpets with infinite bubble joy.",
    germanDescription: "Trötet fröhlich und pustet Myriaden von Zuckerblasen.",
    color: "bg-blue-50 text-blue-700 border-blue-200",
  },
  {
    id: "tiger",
    name: "Cuddle Stripes",
    germanName: "Plüsch-Tigerchen",
    emoji: "🐯",
    image: "/assets/animals/tiger.png",
    baseCost: 1.5e27,
    costMultiplier: 1.23,
    baseLps: 3.0e22,
    count: 0,
    description: "Fiercely snuggly with super-soft velvet claws.",
    germanDescription: "Hat samtweiche Tatzen und schmust für sein Leben gern.",
    color: "bg-[#FFF9C4] text-amber-800 border-amber-200",
  },
  {
    id: "lion",
    name: "Snug Mane",
    germanName: "Kuschel-Löwe",
    emoji: "🦁",
    image: "/assets/animals/lion.png",
    baseCost: 1.0e28,
    costMultiplier: 1.24,
    baseLps: 1.6e23,
    count: 0,
    description: "Shakes a golden constellation mane.",
    germanDescription: "Schüttelt stolz seine Mähne voller Sonnenstrahlen.",
    color: "bg-[#FFF9C4] text-amber-700 border-amber-200",
  },
  {
    id: "monkey",
    name: "Swing-along Max",
    germanName: "Kletter-Max",
    emoji: "🐵",
    image: "/assets/animals/monkey.png",
    baseCost: 6.8e28,
    costMultiplier: 1.24,
    baseLps: 8.5e23,
    count: 0,
    description: "Swings from meteor to meteor.",
    germanDescription: "Hangelt sich akrobatisch von Meteorit zu Meteorit.",
    color: "bg-amber-50 text-amber-850 border-amber-200",
  },
  {
    id: "giraffe",
    name: "Skyreach Susi",
    germanName: "Langhals-Susi",
    emoji: "🦒",
    image: "/assets/animals/giraffe.png",
    baseCost: 4.5e29,
    costMultiplier: 1.24,
    baseLps: 4.5e24,
    count: 0,
    description: "Eats leaves from the highest space shrubs.",
    germanDescription: "Zupft Blätter von den allerhöchsten Satelliten-Bäumen.",
    color: "bg-yellow-50 text-yellow-750 border-yellow-200",
  },
  {
    id: "zebra",
    name: "Pony Pyjamas",
    germanName: "Pony-Zebra",
    emoji: "🦓",
    image: "/assets/animals/zebra.png",
    baseCost: 3.0e30,
    costMultiplier: 1.24,
    baseLps: 2.4e25,
    count: 0,
    description: "Stripes that glow in dark voids.",
    germanDescription: "Trägt lichtsammelnde Streifen für die dunkele Nacht.",
    color: "bg-slate-50 text-slate-700 border-slate-200",
  },
  {
    id: "ram",
    name: "Slumber Horns",
    germanName: "Schlummer-Widder",
    emoji: "🐏",
    image: "/assets/animals/ram.png",
    baseCost: 2.0e31,
    costMultiplier: 1.25,
    baseLps: 1.2e26,
    count: 0,
    description: "Gently heads up fluffy cloud barriers.",
    germanDescription: "Stößt sachte an weiche Hindernisse aus Zuckerwatte.",
    color: "bg-stone-55 text-stone-700 border-stone-200",
  },
  {
    id: "dragon",
    name: "Feather Drake",
    germanName: "Zuckerfee-Drache",
    emoji: "🐲",
    image: "/assets/animals/dragon.png",
    baseCost: 1.3e32,
    costMultiplier: 1.25,
    baseLps: 6.5e26,
    count: 0,
    description: "Breathes lovely sparkling heart puffs.",
    germanDescription: "Speit warme, duftende Funken voller Herzkuchen.",
    color: "bg-rose-50 text-rose-700 border-rose-200",
  },
  {
    id: "doggy",
    name: "Velvet Hound",
    germanName: "Flausch-Hund",
    emoji: "🐕",
    image: "/assets/animals/doggy.png",
    baseCost: 8.5e32,
    costMultiplier: 1.25,
    baseLps: 3.5e27,
    count: 0,
    description: "Licks stars right out of the sky.",
    germanDescription: "Leckt mit Freude Sternschnuppen vom blauen Himmelszelt.",
    color: "bg-amber-50 text-amber-900 border-amber-200",
  },
  {
    id: "dove",
    name: "Feather Coo",
    germanName: "Kuschel-Täubchen",
    emoji: "🕊️",
    image: "/assets/animals/dove.png",
    baseCost: 5.5e33,
    costMultiplier: 1.25,
    baseLps: 1.8e28,
    count: 0,
    description: "Sings peace into the universe hearts.",
    germanDescription: "Girrt Melodien der Eintracht in jeden finsteren Winkel.",
    color: "bg-pink-50 text-pink-700 border-pink-200",
  },
  {
    id: "parrot",
    name: "Macaw Mimic",
    germanName: "Quassel-Kekschen",
    emoji: "🦜",
    image: "/assets/animals/parrot.png",
    baseCost: 3.5e34,
    costMultiplier: 1.26,
    baseLps: 9.5e28,
    count: 0,
    description: "Repeats your click sound with beautiful chirps.",
    germanDescription: "Plappert jedes Klicken herrlich melodisch nach.",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    id: "raccoon",
    name: "Masked Nibbler",
    germanName: "Nasch-Bärchen",
    emoji: "🦝",
    image: "/assets/animals/raccoon.png",
    baseCost: 2.2e35,
    costMultiplier: 1.26,
    baseLps: 4.8e29,
    count: 0,
    description: "Washes meteors in cool water currents.",
    germanDescription: "Wäscht kosmischen Proviant in schwebenden Kometenbecken.",
    color: "bg-stone-100 text-stone-700 border-stone-250",
  },
  {
    id: "kangaroo",
    name: "Joey Carrier",
    germanName: "Kuschel-Känguru",
    emoji: "🦘",
    image: "/assets/animals/kangaroo.png",
    baseCost: 1.4e36,
    costMultiplier: 1.26,
    baseLps: 2.4e30,
    count: 0,
    description: "Bounces with infinite energy levels.",
    germanDescription: "Trägt sein kuscheliges Baby durch himmlische Dünen.",
    color: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "flamingo",
    name: "Sherbet Legs",
    germanName: "Rosa Flamingo",
    emoji: "🦩",
    image: "/assets/animals/flamingo.png",
    baseCost: 9.0e36,
    costMultiplier: 1.26,
    baseLps: 1.2e31,
    count: 0,
    description: "Stands on one leg atop stardust dunes.",
    germanDescription: "Balanciert stundenlang graziös auf nur einem Beinchen.",
    color: "bg-rose-50 text-rose-600 border-rose-200",
  },
  {
    id: "camel",
    name: "Dune Oasis",
    germanName: "Trödel-Kamel",
    emoji: "🐫",
    image: "/assets/animals/camel.png",
    baseCost: 5.8e37,
    costMultiplier: 1.27,
    baseLps: 6.0e31,
    count: 0,
    description: "Carries pure starlight in its humps.",
    germanDescription: "Trägt einen unerschöpflichen Vorrat an Lebensquell mit sich.",
    color: "bg-yellow-50 text-yellow-800 border-yellow-200",
  },
  {
    id: "swan",
    name: "Royal glide",
    germanName: "Prinzessin-Schwan",
    emoji: "🦢",
    image: "/assets/animals/swan.png",
    baseCost: 3.8e38,
    costMultiplier: 1.27,
    baseLps: 3.0e32,
    count: 0,
    description: "Deep elegant feathers of stellar grace.",
    germanDescription: "Breitet seine prachtvollen, weißen Flügel schützend aus.",
    color: "bg-slate-50 text-slate-700 border-slate-200",
  },
  {
    id: "octopus",
    name: "Bubble Tickle",
    germanName: "Okti-Krake",
    emoji: "🐙",
    image: "/assets/animals/octopus.png",
    baseCost: 2.4e39,
    costMultiplier: 1.27,
    baseLps: 1.5e33,
    count: 0,
    description: "Tickles planets with eight soft suckers.",
    germanDescription: "Kitzelt Kometen gleichzeitig mit acht weichen Tentakeln.",
    color: "bg-rose-50 text-rose-700 border-rose-250",
  },
  {
    id: "peacock",
    name: "Showoff Prince",
    germanName: "Kaiser-Pfau",
    emoji: "🦚",
    image: "/assets/animals/peacock.png",
    baseCost: 1.5e40,
    costMultiplier: 1.27,
    baseLps: 7.5e33,
    count: 0,
    description: "Spreads tail feathers like a shimmering galaxy.",
    germanDescription: "Schlägt ein prachtvolles Rad aus schimmerndem Sternengold.",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    id: "phoenix",
    name: "Starfire Phoenix",
    germanName: "Glutschnabel-Phönix",
    emoji: "🐦‍🔥",
    image: "/assets/animals/phoenix.png",
    baseCost: 1.0e41,
    costMultiplier: 1.28,
    baseLps: 3.5e34,
    count: 0,
    description: "Reborn in beautiful streams of candy stardust.",
    germanDescription: "Erhebt sich majestätisch neu aus süßem Sternenstaub.",
    color: "bg-rose-50 text-rose-800 border-rose-300",
  },
];

export function calculateCost(baseCost: number, count: number, multiplier: number): number {
  return Math.floor(baseCost * Math.pow(multiplier, count));
}

export function formatCompactNumber(num: number): string {
  if (num === null || isNaN(num)) return "0";
  if (num < 1000) {
    if (num === 0) return "0";
    return num % 1 === 0 ? num.toString() : num.toFixed(1);
  }
  const suffixes = [
    { value: 1e3, symbol: "K" },
    { value: 1e6, symbol: "M" },
    { value: 1e9, symbol: "B" },
    { value: 1e12, symbol: "T" },
    { value: 1e15, symbol: "Qa" },
    { value: 1e18, symbol: "Qi" },
    { value: 1e21, symbol: "Sx" },
    { value: 1e24, symbol: "Sp" },
    { value: 1e27, symbol: "Oc" },
    { value: 1e30, symbol: "No" },
    { value: 1e33, symbol: "Dc" },
    { value: 1e36, symbol: "Ud" },
    { value: 1e39, symbol: "Dd" },
    { value: 1e42, symbol: "Td" },
    { value: 1e45, symbol: "Qad" },
  ];
  
  for (let i = suffixes.length - 1; i >= 0; i--) {
    if (num >= suffixes[i].value) {
      const formatted = (num / suffixes[i].value).toFixed(2);
      // Clean up trivial trailing decimals (e.g. 1.20 -> 1.2, 1.00 -> 1)
      return parseFloat(formatted) + suffixes[i].symbol;
    }
  }
  return num.toString();
}

/**
 * Dynamically calculates the prestige requirement based on current prestige count.
 * Scales by 2.5x with each prestige in order to prevent consecutively abusing prestige
 * and key users longer in their loops.
 */
export function getPrestigeRequirement(prestigeCount: number): number {
  return 500000000 * Math.pow(2.5, prestigeCount);
}

