import { Animal } from "./types";

const ANIMAL_SPRITE_META = {
  frameWidth: 160,
  frameHeight: 160,
  columns: 6,
  walkFrames: 6,
  liftFrames: 6,
} as const;

function withAnimalSpriteMeta(animal: Animal): Animal {
  if (!animal.image) return animal;

  return {
    ...animal,
    ...ANIMAL_SPRITE_META,
    sheetSrc: `/assets/animals/animated/${animal.id}.webp`,
  };
}

const RAW_INITIAL_ANIMALS: Animal[] = [
  {
    id: "bunny",
    name: "Wooly Bunny",
    germanName: "Wolliges Haeschen",
    emoji: "🐰",
    image: "/assets/animals/bunny.webp",
    baseCost: 15,
    costMultiplier: 1.15,
    baseLps: 0.1,
    count: 0,
    description: "Nibbles on sweet moss and hops around.",
    germanDescription: "Knabbert an suessem Moos und hoppelt froehlich.",
    color: "bg-pink-50 text-pink-600 border-pink-100 selection:bg-pink-100",
  },
  {
    id: "chick",
    name: "Pastel Chick",
    germanName: "Pastell-Kueken",
    emoji: "🐤",
    image: "/assets/animals/chick.webp",
    baseCost: 100,
    costMultiplier: 1.15,
    baseLps: 0.6,
    count: 0,
    description: "Peeps happily and looks for tiny star bits.",
    germanDescription: "Piepst herzerwaermend und sucht glitzernde Kruemel.",
    color: "bg-yellow-50 text-yellow-600 border-yellow-105 selection:bg-yellow-100",
  },
  {
    id: "cat",
    name: "Slumber Kitten",
    germanName: "Schlummer-Kaetzchen",
    emoji: "🐱",
    image: "/assets/animals/cat.webp",
    baseCost: 700,
    costMultiplier: 1.15,
    baseLps: 3.5,
    count: 0,
    description: "Purrs at the rhythm of stellar starlight.",
    germanDescription: "Schnurrt sanft im Rhythmus des kosmischen Sternenstaubs.",
    color: "bg-indigo-50 text-indigo-600 border-indigo-100 selection:bg-indigo-100",
  },
  {
    id: "frog",
    name: "Chubby Frog",
    germanName: "Kuller-Frosch",
    emoji: "🐸",
    image: "/assets/animals/frog.webp",
    baseCost: 4500,
    costMultiplier: 1.15,
    baseLps: 18.0,
    count: 0,
    description: "Hops around fluffy pastel clouds.",
    germanDescription: "Huepft auf weichen, flauschigen Schaefchenwolken.",
    color: "bg-emerald-50 text-emerald-600 border-emerald-100 selection:bg-emerald-100",
  },
  {
    id: "koala",
    name: "Eucalyptus Koala",
    germanName: "Suesser Koala",
    emoji: "🐨",
    image: "/assets/animals/koala.webp",
    baseCost: 28000,
    costMultiplier: 1.15,
    baseLps: 90.0,
    count: 0,
    description: "Hugs the planet and dreams of cozy forests.",
    germanDescription: "Klammert sich fest und traeumt von duftenden Waeldern.",
    color: "bg-slate-100 text-slate-600 border-slate-205 selection:bg-slate-200",
  },
  {
    id: "panda",
    name: "Fluffy Panda",
    germanName: "Flausch-Panda",
    emoji: "🐼",
    image: "/assets/animals/panda.webp",
    baseCost: 180000,
    costMultiplier: 1.15,
    baseLps: 450.0,
    count: 0,
    description: "Rolls around happily in stellar meadows.",
    germanDescription: "Kugelt sich gluecklich im weichen Gras herum.",
    color: "bg-zinc-100 text-zinc-600 border-zinc-200 selection:bg-zinc-200",
  },
  {
    id: "unicorn",
    name: "Rainbow Unicorn",
    germanName: "Regenbogen-Einhorn",
    emoji: "🦄",
    image: "/assets/animals/unicorn.webp",
    baseCost: 1100000,
    costMultiplier: 1.15,
    baseLps: 2200.0,
    count: 0,
    description: "Spreads rainbow glow and sparkly magic.",
    germanDescription: "Versprueht zauberhaften Glitzerregen und Glueckseligkeit.",
    color: "bg-purple-50 text-purple-600 border-purple-100 selection:bg-purple-100",
  },
  {
    id: "hamster",
    name: "Nugget Hamster",
    germanName: "Nugget-Hamster",
    emoji: "🐹",
    image: "/assets/animals/hamster.webp",
    baseCost: 6500000,
    costMultiplier: 1.15,
    baseLps: 11000.0,
    count: 0,
    description: "Stores star energy in its tiny cheeks.",
    germanDescription: "Speichert Sternenstaub-Energie in seinen suessen Baeckchen.",
    color: "bg-amber-50 text-amber-600 border-amber-150",
  },
  {
    id: "fox",
    name: "Cinnamon Fox",
    germanName: "Zimt-Fuechslein",
    emoji: "🦊",
    image: "/assets/animals/fox.webp",
    baseCost: 38000000,
    costMultiplier: 1.15,
    baseLps: 55000.0,
    count: 0,
    description: "Curling its tail around warm stardust.",
    germanDescription: "Kringelt seinen weichen Schwanz um warmen Sternenstaub.",
    color: "bg-orange-50 text-orange-600 border-orange-150",
  },
  {
    id: "bear",
    name: "Honey Bear",
    germanName: "Brumm-Baerchen",
    emoji: "🐻",
    image: "/assets/animals/bear.webp",
    baseCost: 220000000,
    costMultiplier: 1.16,
    baseLps: 280000.0,
    count: 0,
    description: "Gathers sweet celestial honey from nebula hives.",
    germanDescription: "Sammelt himmlisch suessen Honig aus schimmernden Nebeln.",
    color: "bg-yellow-50 text-amber-700 border-yellow-200",
  },
  {
    id: "alpaca",
    name: "Fluffy Alpaca",
    germanName: "Flausch-Alpaka",
    emoji: "🦙",
    image: "/assets/animals/alpaca.webp",
    baseCost: 1300000000,
    costMultiplier: 1.16,
    baseLps: 1400000.0,
    count: 0,
    description: "Clowdy wool that absorbs comet whispers.",
    germanDescription: "Besitzt wolkenaehnliche Wolle, die das Kometenfluestern speichert.",
    color: "bg-pink-50 text-pink-700 border-pink-200",
  },
  {
    id: "penguin",
    name: "Sliding Penguin",
    germanName: "Kuller-Pinguin",
    emoji: "🐧",
    image: "/assets/animals/penguin.webp",
    baseCost: 8000000000,
    costMultiplier: 1.17,
    baseLps: 7000000.0,
    count: 0,
    description: "Slides elegantly on rings of ice.",
    germanDescription: "Rutscht gut gelaunt auf kuehlen Eisringen entlang.",
    color: "bg-sky-50 text-sky-700 border-sky-200",
  },
  {
    id: "sloth",
    name: "Dreamy Sloth",
    germanName: "Schluffi-Faultier",
    emoji: "🦥",
    image: "/assets/animals/sloth.webp",
    baseCost: 50000000000,
    costMultiplier: 1.17,
    baseLps: 35000000.0,
    count: 0,
    description: "Hangs on space branches in peaceful slumber.",
    germanDescription: "Haengt an Sternenaesten und schlaeft seelenruhig.",
    color: "bg-stone-55 text-stone-600 border-stone-200",
  },
  {
    id: "hedgehog",
    name: "Prickly Cookie",
    germanName: "Stachel-Keks",
    emoji: "🦔",
    image: "/assets/animals/hedgehog.webp",
    baseCost: 320000000000,
    costMultiplier: 1.18,
    baseLps: 180000000.0,
    count: 0,
    description: "Rolls up into an adorable sparkly ball.",
    germanDescription: "Rollt sich zu einer glitzernden, niedlichen Kugel zusammen.",
    color: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "seal",
    name: "Chubby Seal",
    germanName: "Kuller-Robbe",
    emoji: "🦭",
    image: "/assets/animals/seal.webp",
    baseCost: 2000000000000,
    costMultiplier: 1.18,
    baseLps: 950000000.0,
    count: 0,
    description: "Bounces with joy on cosmic bubble wrap.",
    germanDescription: "Kullert gluecklich auf kleinen kosmischen Seifenblasen.",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    id: "sheep",
    name: "Cloudy Sheep",
    germanName: "Woelkchen-Schaf",
    emoji: "🐑",
    image: "/assets/animals/sheep.webp",
    baseCost: 13000000000000,
    costMultiplier: 1.18,
    baseLps: 5000000000.0,
    count: 0,
    description: "Looks exactly like a fluffy space cloud.",
    germanDescription: "Sieht aus wie ein kleines Stueckchen sanfter Abendhimmel.",
    color: "bg-slate-55 text-slate-700 border-slate-200",
  },
  {
    id: "otter",
    name: "Tickle Otter",
    germanName: "Kitzel-Otter",
    emoji: "🦦",
    image: "/assets/animals/otter.webp",
    baseCost: 85000000000000,
    costMultiplier: 1.19,
    baseLps: 26000000000.0,
    count: 0,
    description: "Holds hands in the river of starlight.",
    germanDescription: "Haelt Haendchen im sanften Fluss aus purem Sternenlicht.",
    color: "bg-indigo-50 text-indigo-700 border-indigo-200",
  },
  {
    id: "deer",
    name: "Forest Fawn",
    germanName: "Wald-Rehlein",
    emoji: "🦌",
    image: "/assets/animals/deer.webp",
    baseCost: 550000000000000,
    costMultiplier: 1.19,
    baseLps: 140000000000.0,
    count: 0,
    description: "Grows tiny glowing constellations on its back.",
    germanDescription: "Traegt kleine leuchtende Sternbilder auf seinem suessen Fell.",
    color: "bg-amber-50 text-amber-800 border-amber-250",
  },
  {
    id: "dino",
    name: "Tiny Dino",
    germanName: "Zwerg-Dino",
    emoji: "🦖",
    image: "/assets/animals/dino.webp",
    baseCost: 3500000000000000,
    costMultiplier: 1.19,
    baseLps: 750000000000.0,
    count: 0,
    description: "Roars with the tiniest cute squeak.",
    germanDescription: "Bruellt wie ein gaenzlich furchtloser Mini-Vulkan.",
    color: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    id: "duck",
    name: "Squeaky Quacker",
    germanName: "Quack-Entchen",
    emoji: "🦆",
    image: "/assets/animals/duck.webp",
    baseCost: 22000000000000000,
    costMultiplier: 1.2,
    baseLps: 4200000000000.0,
    count: 0,
    description: "Splashes in warm milk canals.",
    germanDescription: "Schwimmt schnatternd im wohlig warmen Sternenmilch-Kanal.",
    color: "bg-yellow-50 text-yellow-700 border-yellow-250",
  },
  {
    id: "ladybug",
    name: "Lucky Beetle",
    germanName: "Puenktchen-Kaefer",
    emoji: "🐞",
    image: "/assets/animals/ladybug.webp",
    baseCost: 150000000000000000,
    costMultiplier: 1.2,
    baseLps: 24000000000000.0,
    count: 0,
    description: "Brings good fortune to every space garden.",
    germanDescription: "Bringt glitzerndes Glueck in jeden kosmischen Garten.",
    color: "bg-rose-50 text-rose-700 border-rose-200",
  },
  {
    id: "bee",
    name: "Buzzing Honeybee",
    germanName: "Suesses Bienchen",
    emoji: "🐝",
    image: "/assets/animals/bee.webp",
    baseCost: 1000000000000000000,
    costMultiplier: 1.2,
    baseLps: 130000000000000.0,
    count: 0,
    description: "Flutters about pollinating pastel blooms.",
    germanDescription: "Bestaeubt tanzend die allerschoensten Seerosen.",
    color: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "pig",
    name: "Piggy Wiggy",
    germanName: "Rosa Kuschelschwein",
    emoji: "🐷",
    image: "/assets/animals/pig.webp",
    baseCost: 7.0e18,
    costMultiplier: 1.21,
    baseLps: 7.5e14,
    count: 0,
    description: "Loves mudbaths in sparkling hot springs.",
    germanDescription: "Wuehlt am liebsten in glitzerndem Thermalbaederschlamm herum.",
    color: "bg-pink-50 text-pink-700 border-pink-200",
  },
  {
    id: "puppy",
    name: "Paw Puppeteer",
    germanName: "Tapsi-Welpe",
    emoji: "🐶",
    image: "/assets/animals/puppy.webp",
    baseCost: 4.8e19,
    costMultiplier: 1.21,
    baseLps: 4.5e15,
    count: 0,
    description: "Wags its tail at supersonic speed.",
    germanDescription: "Wedelt so schnell mit dem Schwanz, dass Sterne funkeln.",
    color: "bg-orange-50 text-orange-700 border-orange-200",
  },
  {
    id: "squirrel",
    name: "Hazelnut Scurrier",
    germanName: "Knusper-Hoernchen",
    emoji: "🐿️",
    image: "/assets/animals/squirrel.webp",
    baseCost: 3.2e20,
    costMultiplier: 1.21,
    baseLps: 2.5e16,
    count: 0,
    description: "Hides golden glowing space nuts.",
    germanDescription: "Versteckt goldene Zaubernuesse im galaktischen Boden.",
    color: "bg-amber-50 text-amber-800 border-amber-200",
  },
  {
    id: "mouse",
    name: "Sugar Mouse",
    germanName: "Zucker-Maeuschen",
    emoji: "🐭",
    image: "/assets/animals/mouse.webp",
    baseCost: 2.2e21,
    costMultiplier: 1.22,
    baseLps: 1.4e17,
    count: 0,
    description: "Squeaks sweet lullabies to sleeping planets.",
    germanDescription: "Piepst Melodien fuer schlafende Monde und Zwergsterne.",
    color: "bg-zinc-50 text-zinc-600 border-zinc-200",
  },
  {
    id: "turtle",
    name: "Cosmic Shellback",
    germanName: "Troedel-Schildi",
    emoji: "🐢",
    image: "/assets/animals/turtle.webp",
    baseCost: 1.5e22,
    costMultiplier: 1.22,
    baseLps: 8.5e17,
    count: 0,
    description: "Carries a miniature ecosystem on its shell.",
    germanDescription: "Traegt eine winzige Tropeninsel spazieren.",
    color: "bg-emerald-50 text-emerald-700 border-emerald-200",
  },
  {
    id: "owl",
    name: "Sage Gazer",
    germanName: "Glubsch-Eule",
    emoji: "🦉",
    image: "/assets/animals/owl.webp",
    baseCost: 1.0e23,
    costMultiplier: 1.22,
    baseLps: 5.0e18,
    count: 0,
    description: "Harnesses wisecracking cosmic insight.",
    germanDescription: "Schaut majestaetisch tief in die unendlichen Weiten.",
    color: "bg-indigo-50 text-indigo-700 border-indigo-200",
  },
  {
    id: "dolphin",
    name: "Splash Glitter",
    germanName: "Glitzer-Delfin",
    emoji: "🐬",
    image: "/assets/animals/dolphin.webp",
    baseCost: 7.0e23,
    costMultiplier: 1.15,
    baseLps: 3.0e19,
    count: 0,
    description: "Leaps through nebulas leaving sparkly trails.",
    germanDescription: "Springt elegant durch Wolken aus buntem Sternenstaub.",
    color: "bg-sky-50 text-sky-700 border-sky-200",
  },
  {
    id: "whale",
    name: "Nebula Whale",
    germanName: "Himmels-Wal",
    emoji: "🐳",
    image: "/assets/animals/whale.webp",
    baseCost: 4.8e24,
    costMultiplier: 1.23,
    baseLps: 1.8e20,
    count: 0,
    description: "Sings ultrasonic stellar tunes.",
    germanDescription: "Singt Lieder, die ganze Galaxien zum Leuchten bringen.",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    id: "butterfly",
    name: "Nectar Flutter",
    germanName: "Flatter-Mops",
    emoji: "🦋",
    image: "/assets/animals/butterfly.webp",
    baseCost: 3.2e25,
    costMultiplier: 1.23,
    baseLps: 1.0e21,
    count: 0,
    description: "Gently bats sparkly wings of light.",
    germanDescription: "Sorgt fuer sanfte Wirbelstuerme aus buntem Glueckspuder.",
    color: "bg-purple-50 text-purple-700 border-purple-200",
  },
  {
    id: "elephant",
    name: "Bouncing Ellie",
    germanName: "Kuller-Kathi",
    emoji: "🐘",
    image: "/assets/animals/elephant.webp",
    baseCost: 2.2e26,
    costMultiplier: 1.23,
    baseLps: 5.5e21,
    count: 0,
    description: "Trumpets with infinite bubble joy.",
    germanDescription: "Troetet froehlich und pustet Myriaden von Zuckerblasen.",
    color: "bg-blue-50 text-blue-700 border-blue-200",
  },
  {
    id: "tiger",
    name: "Cuddle Stripes",
    germanName: "Pluesch-Tigerchen",
    emoji: "🐯",
    image: "/assets/animals/tiger.webp",
    baseCost: 1.5e27,
    costMultiplier: 1.23,
    baseLps: 3.0e22,
    count: 0,
    description: "Fiercely snuggly with super-soft velvet claws.",
    germanDescription: "Hat samtweiche Tatzen und schmust fuer sein Leben gern.",
    color: "bg-brand-yellow text-amber-800 border-amber-200",
  },
  {
    id: "lion",
    name: "Snug Mane",
    germanName: "Kuschel-Loewe",
    emoji: "🦁",
    image: "/assets/animals/lion.webp",
    baseCost: 1.0e28,
    costMultiplier: 1.24,
    baseLps: 1.6e23,
    count: 0,
    description: "Shakes a golden constellation mane.",
    germanDescription: "Schuettelt stolz seine Maehne voller Sonnenstrahlen.",
    color: "bg-brand-yellow text-amber-700 border-amber-200",
  },
  {
    id: "monkey",
    name: "Swing-along Max",
    germanName: "Kletter-Max",
    emoji: "🐵",
    image: "/assets/animals/monkey.webp",
    baseCost: 6.8e28,
    costMultiplier: 1.24,
    baseLps: 8.5e23,
    count: 0,
    description: "Swings from meteor to meteor.",
    germanDescription: "Hangelt sich akrobatisch von Meteorit zu Meteorit.",
    color: "bg-amber-50 text-amber-850 border-amber-200",
  },
  {
    id: "giraffe",
    name: "Skyreach Susi",
    germanName: "Langhals-Susi",
    emoji: "🦒",
    image: "/assets/animals/giraffe.webp",
    baseCost: 4.5e29,
    costMultiplier: 1.24,
    baseLps: 4.5e24,
    count: 0,
    description: "Eats leaves from the highest space shrubs.",
    germanDescription: "Zupft Blaetter von den allerhoechsten Satelliten-Baeumen.",
    color: "bg-yellow-50 text-yellow-750 border-yellow-200",
  },
  {
    id: "zebra",
    name: "Pony Pyjamas",
    germanName: "Pony-Zebra",
    emoji: "🦓",
    image: "/assets/animals/zebra.webp",
    baseCost: 3.0e30,
    costMultiplier: 1.24,
    baseLps: 2.4e25,
    count: 0,
    description: "Stripes that glow in dark voids.",
    germanDescription: "Traegt lichtsammelnde Streifen fuer die dunkele Nacht.",
    color: "bg-slate-50 text-slate-700 border-slate-200",
  },
  {
    id: "ram",
    name: "Slumber Horns",
    germanName: "Schlummer-Widder",
    emoji: "🐏",
    image: "/assets/animals/ram.webp",
    baseCost: 2.0e31,
    costMultiplier: 1.25,
    baseLps: 1.2e26,
    count: 0,
    description: "Gently heads up fluffy cloud barriers.",
    germanDescription: "Stoesst sachte an weiche Hindernisse aus Zuckerwatte.",
    color: "bg-stone-55 text-stone-700 border-stone-200",
  },
  {
    id: "dragon",
    name: "Feather Drake",
    germanName: "Zuckerfee-Drache",
    emoji: "🐲",
    image: "/assets/animals/dragon.webp",
    baseCost: 1.3e32,
    costMultiplier: 1.25,
    baseLps: 6.5e26,
    count: 0,
    description: "Breathes lovely sparkling heart puffs.",
    germanDescription: "Speit warme, duftende Funken voller Herzkuchen.",
    color: "bg-rose-50 text-rose-700 border-rose-200",
  },
  {
    id: "doggy",
    name: "Velvet Hound",
    germanName: "Flausch-Hund",
    emoji: "🐕",
    image: "/assets/animals/doggy.webp",
    baseCost: 8.5e32,
    costMultiplier: 1.25,
    baseLps: 3.5e27,
    count: 0,
    description: "Licks stars right out of the sky.",
    germanDescription: "Leckt mit Freude Sternschnuppen vom blauen Himmelszelt.",
    color: "bg-amber-50 text-amber-900 border-amber-200",
  },
  {
    id: "dove",
    name: "Feather Coo",
    germanName: "Kuschel-Taeubchen",
    emoji: "🕊️",
    image: "/assets/animals/dove.webp",
    baseCost: 5.5e33,
    costMultiplier: 1.25,
    baseLps: 1.8e28,
    count: 0,
    description: "Sings peace into the universe hearts.",
    germanDescription: "Girrt Melodien der Eintracht in jeden finsteren Winkel.",
    color: "bg-pink-50 text-pink-700 border-pink-200",
  },
  {
    id: "parrot",
    name: "Macaw Mimic",
    germanName: "Quassel-Kekschen",
    emoji: "🦜",
    image: "/assets/animals/parrot.webp",
    baseCost: 3.5e34,
    costMultiplier: 1.26,
    baseLps: 9.5e28,
    count: 0,
    description: "Repeats your click sound with beautiful chirps.",
    germanDescription: "Plappert jedes Klicken herrlich melodisch nach.",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    id: "raccoon",
    name: "Masked Nibbler",
    germanName: "Nasch-Baerchen",
    emoji: "🦝",
    image: "/assets/animals/raccoon.webp",
    baseCost: 2.2e35,
    costMultiplier: 1.26,
    baseLps: 4.8e29,
    count: 0,
    description: "Washes meteors in cool water currents.",
    germanDescription: "Waescht kosmischen Proviant in schwebenden Kometenbecken.",
    color: "bg-stone-100 text-stone-700 border-stone-250",
  },
  {
    id: "kangaroo",
    name: "Joey Carrier",
    germanName: "Kuschel-Kaenguru",
    emoji: "🦘",
    image: "/assets/animals/kangaroo.webp",
    baseCost: 1.4e36,
    costMultiplier: 1.26,
    baseLps: 2.4e30,
    count: 0,
    description: "Bounces with infinite energy levels.",
    germanDescription: "Traegt sein kuscheliges Baby durch himmlische Duenen.",
    color: "bg-amber-50 text-amber-700 border-amber-200",
  },
  {
    id: "flamingo",
    name: "Sherbet Legs",
    germanName: "Rosa Flamingo",
    emoji: "🦩",
    image: "/assets/animals/flamingo.webp",
    baseCost: 9.0e36,
    costMultiplier: 1.26,
    baseLps: 1.2e31,
    count: 0,
    description: "Stands on one leg atop stardust dunes.",
    germanDescription: "Balanciert stundenlang grazioes auf nur einem Beinchen.",
    color: "bg-rose-50 text-rose-600 border-rose-200",
  },
  {
    id: "camel",
    name: "Dune Oasis",
    germanName: "Troedel-Kamel",
    emoji: "🐫",
    image: "/assets/animals/camel.webp",
    baseCost: 5.8e37,
    costMultiplier: 1.27,
    baseLps: 6.0e31,
    count: 0,
    description: "Carries pure starlight in its humps.",
    germanDescription: "Traegt einen unerschoepflichen Vorrat an Lebensquell mit sich.",
    color: "bg-yellow-50 text-yellow-800 border-yellow-200",
  },
  {
    id: "swan",
    name: "Royal glide",
    germanName: "Prinzessin-Schwan",
    emoji: "🦢",
    image: "/assets/animals/swan.webp",
    baseCost: 3.8e38,
    costMultiplier: 1.27,
    baseLps: 3.0e32,
    count: 0,
    description: "Deep elegant feathers of stellar grace.",
    germanDescription: "Breitet seine prachtvollen, weissen Fluegel schuetzend aus.",
    color: "bg-slate-50 text-slate-700 border-slate-200",
  },
  {
    id: "octopus",
    name: "Bubble Tickle",
    germanName: "Okti-Krake",
    emoji: "🐙",
    image: "/assets/animals/octopus.webp",
    baseCost: 2.4e39,
    costMultiplier: 1.27,
    baseLps: 1.5e33,
    count: 0,
    description: "Tickles planets with eight soft suckers.",
    germanDescription: "Kitzelt Kometen gleichzeitig mit acht weichen Tentakeln.",
    color: "bg-rose-50 text-rose-700 border-rose-250",
  },
  {
    id: "peacock",
    name: "Showoff Prince",
    germanName: "Kaiser-Pfau",
    emoji: "🦚",
    image: "/assets/animals/peacock.webp",
    baseCost: 1.5e40,
    costMultiplier: 1.27,
    baseLps: 7.5e33,
    count: 0,
    description: "Spreads tail feathers like a shimmering galaxy.",
    germanDescription: "Schlaegt ein prachtvolles Rad aus schimmerndem Sternengold.",
    color: "bg-teal-50 text-teal-700 border-teal-200",
  },
  {
    id: "phoenix",
    name: "Starfire Phoenix",
    germanName: "Glutschnabel-Phoenix",
    emoji: "🐦‍🔥",
    image: "/assets/animals/phoenix.webp",
    baseCost: 1.0e41,
    costMultiplier: 1.28,
    baseLps: 3.5e34,
    count: 0,
    description: "Reborn in beautiful streams of candy stardust.",
    germanDescription: "Erhebt sich majestaetisch neu aus suessem Sternenstaub.",
    color: "bg-rose-50 text-rose-800 border-rose-300",
  },
];

export const INITIAL_ANIMALS: Animal[] = RAW_INITIAL_ANIMALS.map(withAnimalSpriteMeta);

export function calculateCost(baseCost: number, count: number, multiplier: number): number {
  return Math.floor(baseCost * Math.pow(multiplier, count));
}

export { formatCompactNumber } from "./utils/format";

/**
 * Dynamically calculates the prestige requirement based on current prestige count.
 * Scales by 2.5x with each prestige in order to prevent consecutively abusing prestige
 * and key users longer in their loops.
 */
export function getPrestigeRequirement(prestigeCount: number): number {
  return 500000000 * Math.pow(2.5, prestigeCount);
}
